# ========== 自定义 ==========
# 服务端口号
server:
  port: 8080

# 代理配置
proxy:
  # 访问目标站点所用代理（除 free-ss）
  enable: true
  host: 206.189.191.238
  port: 3128

  # 访问 free-ss 时所用代理
  free-ss:
    enable: true
    host: 149.56.27.45
    port: 1080
    socks: true


# driver 路径
driver:
  path: D:\MicrosoftWebDriver.exe

# spring boot 启用调试模式
debug:  false


# ========== Spring ==========
spring:
  # Spring 数据库
  datasource:
    platform: h2
    driver-class-name:  org.h2.Driver
    url:  jdbc:h2:~/test
    username: sa
    password: unrDG0Nb3r4l
